# Generated by Django 4.1.3 on 2022-12-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_commentofcomment_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='commentofcomment',
            name='parent_Comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.comment'),
            preserve_default=False,
        ),
    ]
