# Generated by Django 3.2.6 on 2022-12-17 13:06

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_comment_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='introduction',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
