# Generated by Django 3.2.6 on 2022-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_book_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
