# Generated by Django 3.2.6 on 2022-12-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_comment_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_preview',
        ),
    ]
